# Generated by Django 5.0.6 on 2024-07-07 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_num', models.IntegerField()),
                ('dry_waste', models.IntegerField()),
                ('wet_waste', models.IntegerField()),
                ('e_waste', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MEmployee',
            fields=[
                ('m_phn_no', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('m_name', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
                ('m_sex', models.CharField(max_length=10)),
                ('m_salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('t_num', models.IntegerField(primary_key=True, serialize=False)),
                ('t_time', models.TimeField()),
                ('t_date', models.DateField()),
                ('m_phn_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('sex', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DryWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ap1.bin')),
            ],
        ),
        migrations.CreateModel(
            name='EWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ap1.bin')),
            ],
        ),
        migrations.CreateModel(
            name='MEmployeeEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('m_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ap1.memployee')),
            ],
        ),
        migrations.CreateModel(
            name='Carries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ap1.bin')),
                ('t_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ap1.truck')),
            ],
        ),
        migrations.CreateModel(
            name='TruckLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('t_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ap1.truck')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('credits', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('offer_used', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ap1.user')),
            ],
        ),
        migrations.AddField(
            model_name='bin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ap1.user'),
        ),
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ap1.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ap1.user')),
            ],
        ),
        migrations.CreateModel(
            name='WetWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ap1.bin')),
            ],
        ),
    ]
